name: Build
on: push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build for ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go build -o react ./...
      - run: go vet ./...
      - name: zip linux artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: zip linux.zip react

  build-windows:
    runs-on: windows-latest
    name: Build for windows
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go build -o react ./...
      - run: go vet ./...
      - name: zip windows artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: powershell Compress-Archive react windows.zip

  build-macos:
    runs-on: macos-latest
    name: Build for macos
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go build -o react ./...
      - run: go vet ./...
      - name: zip macos artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: zip macos.zip react

  upload-release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux, build-windows]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: uploads
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./uploads/macos.zip
            ./uploads/linux.zip
            ./uploads/windows.zip
