name: Build
on: push
jobs:
  build:
    strategy:
      matrix:
        host: [ 'windows-latest', 'ubuntu-latest' ]
    runs-on: ${{ matrix.host }}
    name: Build on ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go build -o react ./...
      - run: go vet ./...
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: react
